### ISSUE TITLE
Cannot load class ace.actually.almanac.AlmanacClient in environment type SERVER

### ISSUE THREAD

**Issue by johndelker** [JSJBDEV/Almanac#3]
I'm using version 0.60 with Fabric 1.20.1 and the latest version of Spyglass Astronomy. I'm having multiple problems that make the mod unusable. 

* When I sneak and right click on a cartography table, it says both the fail and success messages. I'm not sure if this matters, but the almanac does not have a version number or which players authored it, which makes me assume it did not work.
* When I right click without sneaking and while holding the almanac, nothing happens, except the server throws an error, which I'll paste below. 
* I can't copy the almanac, though I assume it can only be copied if it has data on it.

It looks like the 0.60 update says it made the mod work with dedicated servers, which I am running, but it doesn't seem to be working. My server is full of professional astronomers, so I'm really hoping we can get it to work.

```

java.lang.RuntimeException: Cannot load class ace.actually.almanac.AlmanacClient in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at ace.actually.almanac.items.AlmanacItem.method_7836(AlmanacItem.java:42) ~[Almanac-0.6.0.jar:?]
	at net.minecraft.class_1799.method_7913(class_1799.java:284) ~[server-intermediary.jar:?]
	at net.minecraft.class_3225.method_14256(class_3225.java:290) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12065(class_3244.java:1177) ~[server-intermediary.jar:?]
	at net.minecraft.class_2886.method_12550(class_2886.java:29) ~[server-intermediary.jar:?]
	at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:14818) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by JSJBDEV** [comment]
Yeah this seems to be a loading issue that I thought I solved, but it might be different in this case. I'll have a look, should be reasonable to fix.

**Comment by JSJBDEV** [comment]
have a look at https://modrinth.com/mod/almanac-for-spyglass-astronomy/version/0.6.1 once it is approved, im fairly sure its fixed now, but test with your server :)

**Comment by johndelker** [comment]
Works great now! Thank you so much!
